spring.application.name=bbs-api

spring.main.allow-bean-definition-overriding=true

spring.security.oauth2.resourceserver.jwt.secret-key=MzFGNEY1QjZDMTAyMzQ1Njc4OUFCQ0ZERjEwQkNF
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS256
spring.security.oauth2.resourceserver.jwt.audiences=api-bbs

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=s9F8vR3eZ1pLkD6mQxWyTnU2oBaScE4hG7IjKlMzNvXpYtWrVbCuFsGeHdJkLzMn
jwt.expiration=86400000
