spring.application.name=bbs-api
spring.profiles.active=dev

spring.main.allow-bean-definition-overriding=true

spring.security.oauth2.resourceserver.jwt.secret-key=MzFGNEY1QjZDMTAyMzQ1Njc4OUFCQ0ZERjEwQkNF
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS256
spring.security.oauth2.resourceserver.jwt.audiences=api-bbs

spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=s9F8vR3eZ1pLkD6mQxWyTnU2oBaScE4hG7IjKlMzNvXpYtWrVbCuFsGeHdJkLzMn
jwt.expiration=86400000
