## configuration file for development environment
spring.datasource.url=jdbc:postgresql://localhost:15432/bbs
spring.datasource.username=java
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# https://tech.excite.co.jp/entry/2024/12/09/110757
spring.docker.compose.stop.command=down
spring.docker.compose.start.log-level=debug

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.validator=DEBUG
